language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y aspell aspell-fr libenchant-dev

install:
  - "pip install pylint"
  - "pip install -r requirements.txt"

script:
  - pylint --disable=W0511 msgcheck
  - pylint --disable=W0511 tests
  - nosetests
